version: "3.7"
services:
  car_travel:
    build: .
    container_name: carTavel-1.0
    #    restart: always
    environment:
      DB_HOST: app_db
    ports:
      - 9000:8080
    depends_on:
      - app_db
    links:
      - app_db
  app_db:
    image: "postgres:13"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root