version: "3.7"
services:
  car_travel:
    build: .
    container_name: carTavel-1.0
    ports:
      - 9000:8080
    depends_on:
      - app_db
    links:
      - app_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://app_db:5432/my_database
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
  app_db:
    image: "postgres:14.1"
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_database
