version: "3.7"
services:
  car_travel:
    build: .
    container_name: carTavel-1.0
    #    restart: always
    env_file:
        - ./database.env
    ports:
      - 9000:8080
    depends_on:
      - app_db
    links:
      - app_db
  app_db:
    image: "postgres:15.2"
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./database.env
