name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install
        env:
          POSTGRES_HOST: app_db
          POSTGRES_PORT: 5432
          POSTGRES_DB: my_database
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
#          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
#          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
#          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
#          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
#          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

